import { Poppins, Inter, K2D } from "next/font/google";
import "./globals.css";
import Header from "./components/General/Header";
import Topheader from "./components/General/topheader";
import Footer from "./components/General/Footer";


const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins",
  style: ["normal", "italic"],
  preload: true,
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Set your desired font weight here. The default is 400.
});

const inter = Inter({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--inter",
  preload: true,
  // weight: ["400", "500", "600", "700", "800", "900"], // Set your desired font weight here. The default is 400.
});
const k2d = K2D({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--k2d",
  preload: true,
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} ${inter.variable} ${k2d.variable}`}
      >
        <Topheader/>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
